[tox]
isolated_build = True
envlist =
    style,
    docstyle,
    check-manifest,
    check-headers

# =============================================================================
# ENVS
# =============================================================================


[testenv:style]
description = "Runs code style checks with flake8 to ensure consistency and quality"
labels = static
skip_install = True
usedevelop = False
deps =
    tomli
    flake8
    flake8-import-order
    flake8-black
    flake8-builtins
commands =
        flake8 volcanicus/ {posargs}


[testenv:docstyle]
description = "Verifies documentation style following NumPy convention"
labels = static
skip_install = True
deps =
    tomli
    pydocstyle
    toml
commands =
    pydocstyle volcanicus/ --convention=numpy --add-ignore=D401


[testenv:check-manifest]
description = "Verifies that the MANIFEST.in file includes all necessary files for distribution"
labels = static
skip_install = True
usedevelop = False
deps = check-manifest
commands =
    check-manifest


[testenv:check-headers]
description = "Ensures all files have the correct headers according to the defined template"
labels = static
skip_install = True
deps =
    https://github.com/quatrope/qafan/archive/refs/heads/master.zip
commands =
    check-headers check volcanicus/ --header-template .header-template {posargs}
